///////////////////////////////////////////////////////////
//  IEventDeclaration.cs
//  Implementation of the Interface IEventDeclaration
//  Generated by Enterprise Architect
//  Created on:      14-8-2010 11:20:08
//  Original author: Administrator
///////////////////////////////////////////////////////////




namespace Urasandesu.NAnonym.CREUtilities {
	public interface IEventDeclaration {

	}//end IEventDeclaration

}//end namespace å^ç\ë¢