///////////////////////////////////////////////////////////
//  ILabelDeclaration.cs
//  Implementation of the Interface ILabelDeclaration
//  Generated by Enterprise Architect
//  Created on:      14-8-2010 11:20:09
//  Original author: Administrator
///////////////////////////////////////////////////////////




namespace Urasandesu.NAnonym.CREUtilities {
	public interface ILabelDeclaration {

	}//end ILabelDeclaration

}//end namespace å^ç\ë¢